### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by atherdon** [Bojan-Lukic-994/250-steps#1]
.

**Comment by Bojan-Lukic-994** [comment]
Hi, Arhtur.

My name is Bojan Lukic, from Serbia. I've only recently (about a month ago) started to learn programming and development - Java and working in Eclipse. I'm a beginner in this. For the future, my main goal is to learn Android programming, but i'm open to learn more than just about Android.
I'm interested in participating in projects, learning and gaining experience. I don't have any experience because i have never worked on any project, and this would be my first one. 

Regards, 
Bojan.

**Comment by Bojan-Lukic-994** [comment]
Hi, @atherdon <https://github.com/atherdon>.

My name is Bojan Lukic, from Serbia. I've only recently (about a month ago)
started to learn programming and development - Java and working in Eclipse.
I'm a beginner in this. For the future, my main goal is to learn Android
programming, but i'm open to learn more than just about Android.
I'm interested in participating in projects, learning and gaining
experience. I don't have any experience because i have never worked on any
project, and this would be my first one.

Regards,
Bojan.
